//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceMantenedorBodega {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorBodega.WebServiceMantenedorBodegaSoap")]
    public interface WebServiceMantenedorBodegaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webGuardarTransaccionBodega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webGuardarTransaccionBodega(CapaGUI.ServiceMantenedorBodega.bodega bod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webGuardarTransaccionBodega", ReplyAction="*")]
        System.Threading.Tasks.Task webGuardarTransaccionBodegaAsync(CapaGUI.ServiceMantenedorBodega.bodega bod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webActualizarBodega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webActualizarBodega(CapaGUI.ServiceMantenedorBodega.bodega bodega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webActualizarBodega", ReplyAction="*")]
        System.Threading.Tasks.Task webActualizarBodegaAsync(CapaGUI.ServiceMantenedorBodega.bodega bodega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webEliminarBodega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webEliminarBodega(string codigo_bodega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webEliminarBodega", ReplyAction="*")]
        System.Threading.Tasks.Task webEliminarBodegaAsync(string codigo_bodega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webConsultaBodega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webConsultaBodega();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webConsultaBodega", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webConsultaBodegaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webPosicionBodega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceMantenedorBodega.bodega webPosicionBodega(int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webPosicionBodega", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceMantenedorBodega.bodega> webPosicionBodegaAsync(int pos);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class bodega : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_bodegaField;
        
        private string nombre_bodegaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Codigo_bodega {
            get {
                return this.codigo_bodegaField;
            }
            set {
                this.codigo_bodegaField = value;
                this.RaisePropertyChanged("Codigo_bodega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre_bodega {
            get {
                return this.nombre_bodegaField;
            }
            set {
                this.nombre_bodegaField = value;
                this.RaisePropertyChanged("Nombre_bodega");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorBodegaSoapChannel : CapaGUI.ServiceMantenedorBodega.WebServiceMantenedorBodegaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorBodegaSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceMantenedorBodega.WebServiceMantenedorBodegaSoap>, CapaGUI.ServiceMantenedorBodega.WebServiceMantenedorBodegaSoap {
        
        public WebServiceMantenedorBodegaSoapClient() {
        }
        
        public WebServiceMantenedorBodegaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorBodegaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorBodegaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorBodegaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void webGuardarTransaccionBodega(CapaGUI.ServiceMantenedorBodega.bodega bod) {
            base.Channel.webGuardarTransaccionBodega(bod);
        }
        
        public System.Threading.Tasks.Task webGuardarTransaccionBodegaAsync(CapaGUI.ServiceMantenedorBodega.bodega bod) {
            return base.Channel.webGuardarTransaccionBodegaAsync(bod);
        }
        
        public void webActualizarBodega(CapaGUI.ServiceMantenedorBodega.bodega bodega) {
            base.Channel.webActualizarBodega(bodega);
        }
        
        public System.Threading.Tasks.Task webActualizarBodegaAsync(CapaGUI.ServiceMantenedorBodega.bodega bodega) {
            return base.Channel.webActualizarBodegaAsync(bodega);
        }
        
        public void webEliminarBodega(string codigo_bodega) {
            base.Channel.webEliminarBodega(codigo_bodega);
        }
        
        public System.Threading.Tasks.Task webEliminarBodegaAsync(string codigo_bodega) {
            return base.Channel.webEliminarBodegaAsync(codigo_bodega);
        }
        
        public System.Data.DataSet webConsultaBodega() {
            return base.Channel.webConsultaBodega();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webConsultaBodegaAsync() {
            return base.Channel.webConsultaBodegaAsync();
        }
        
        public CapaGUI.ServiceMantenedorBodega.bodega webPosicionBodega(int pos) {
            return base.Channel.webPosicionBodega(pos);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceMantenedorBodega.bodega> webPosicionBodegaAsync(int pos) {
            return base.Channel.webPosicionBodegaAsync(pos);
        }
    }
}
