//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceMantenedorProducto {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorProducto.WebServiceMantenedorProductoSoap")]
    public interface WebServiceMantenedorProductoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebGuardarTransaccion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WebGuardarTransaccion(CapaGUI.ServiceMantenedorProducto.productos registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebGuardarTransaccion", ReplyAction="*")]
        System.Threading.Tasks.Task WebGuardarTransaccionAsync(CapaGUI.ServiceMantenedorProducto.productos registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebConsultaProductos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebConsultaProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebConsultaProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebConsultaProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebListaProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebListaProductoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebEliminarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WebEliminarProducto(string cod_producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebEliminarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task WebEliminarProductoAsync(string cod_producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActualizarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WebActualizarProducto(CapaGUI.ServiceMantenedorProducto.productos producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActualizarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task WebActualizarProductoAsync(CapaGUI.ServiceMantenedorProducto.productos producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebPosicionProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceMantenedorProducto.productos WebPosicionProducto(int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebPosicionProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceMantenedorProducto.productos> WebPosicionProductoAsync(int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebEntradaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WebEntradaProducto(CapaGUI.ServiceMantenedorProducto.productos registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebEntradaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task WebEntradaProductoAsync(CapaGUI.ServiceMantenedorProducto.productos registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebSalidaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WebSalidaProducto(CapaGUI.ServiceMantenedorProducto.productos registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebSalidaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task WebSalidaProductoAsync(CapaGUI.ServiceMantenedorProducto.productos registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool WebLogin(CapaGUI.ServiceMantenedorProducto.login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> WebLoginAsync(CapaGUI.ServiceMantenedorProducto.login login);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class productos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cod_productoField;
        
        private string nom_productoField;
        
        private System.DateTime fecha_ingresoField;
        
        private int cantidadField;
        
        private string rut_provField;
        
        private float precio_unitarioField;
        
        private string especificacionesField;
        
        private string condicionField;
        
        private string codigo_bodegaField;
        
        private string rut_bodegueroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Cod_producto {
            get {
                return this.cod_productoField;
            }
            set {
                this.cod_productoField = value;
                this.RaisePropertyChanged("Cod_producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nom_producto {
            get {
                return this.nom_productoField;
            }
            set {
                this.nom_productoField = value;
                this.RaisePropertyChanged("Nom_producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Fecha_ingreso {
            get {
                return this.fecha_ingresoField;
            }
            set {
                this.fecha_ingresoField = value;
                this.RaisePropertyChanged("Fecha_ingreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Rut_prov {
            get {
                return this.rut_provField;
            }
            set {
                this.rut_provField = value;
                this.RaisePropertyChanged("Rut_prov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public float Precio_unitario {
            get {
                return this.precio_unitarioField;
            }
            set {
                this.precio_unitarioField = value;
                this.RaisePropertyChanged("Precio_unitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Especificaciones {
            get {
                return this.especificacionesField;
            }
            set {
                this.especificacionesField = value;
                this.RaisePropertyChanged("Especificaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Condicion {
            get {
                return this.condicionField;
            }
            set {
                this.condicionField = value;
                this.RaisePropertyChanged("Condicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Codigo_bodega {
            get {
                return this.codigo_bodegaField;
            }
            set {
                this.codigo_bodegaField = value;
                this.RaisePropertyChanged("Codigo_bodega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Rut_bodeguero {
            get {
                return this.rut_bodegueroField;
            }
            set {
                this.rut_bodegueroField = value;
                this.RaisePropertyChanged("Rut_bodeguero");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class login : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string contrasenaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("Contrasena");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorProductoSoapChannel : CapaGUI.ServiceMantenedorProducto.WebServiceMantenedorProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorProductoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceMantenedorProducto.WebServiceMantenedorProductoSoap>, CapaGUI.ServiceMantenedorProducto.WebServiceMantenedorProductoSoap {
        
        public WebServiceMantenedorProductoSoapClient() {
        }
        
        public WebServiceMantenedorProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WebGuardarTransaccion(CapaGUI.ServiceMantenedorProducto.productos registro) {
            base.Channel.WebGuardarTransaccion(registro);
        }
        
        public System.Threading.Tasks.Task WebGuardarTransaccionAsync(CapaGUI.ServiceMantenedorProducto.productos registro) {
            return base.Channel.WebGuardarTransaccionAsync(registro);
        }
        
        public System.Data.DataSet WebConsultaProductos() {
            return base.Channel.WebConsultaProductos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebConsultaProductosAsync() {
            return base.Channel.WebConsultaProductosAsync();
        }
        
        public System.Data.DataSet WebListaProducto() {
            return base.Channel.WebListaProducto();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebListaProductoAsync() {
            return base.Channel.WebListaProductoAsync();
        }
        
        public void WebEliminarProducto(string cod_producto) {
            base.Channel.WebEliminarProducto(cod_producto);
        }
        
        public System.Threading.Tasks.Task WebEliminarProductoAsync(string cod_producto) {
            return base.Channel.WebEliminarProductoAsync(cod_producto);
        }
        
        public void WebActualizarProducto(CapaGUI.ServiceMantenedorProducto.productos producto) {
            base.Channel.WebActualizarProducto(producto);
        }
        
        public System.Threading.Tasks.Task WebActualizarProductoAsync(CapaGUI.ServiceMantenedorProducto.productos producto) {
            return base.Channel.WebActualizarProductoAsync(producto);
        }
        
        public CapaGUI.ServiceMantenedorProducto.productos WebPosicionProducto(int pos) {
            return base.Channel.WebPosicionProducto(pos);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceMantenedorProducto.productos> WebPosicionProductoAsync(int pos) {
            return base.Channel.WebPosicionProductoAsync(pos);
        }
        
        public void WebEntradaProducto(CapaGUI.ServiceMantenedorProducto.productos registro) {
            base.Channel.WebEntradaProducto(registro);
        }
        
        public System.Threading.Tasks.Task WebEntradaProductoAsync(CapaGUI.ServiceMantenedorProducto.productos registro) {
            return base.Channel.WebEntradaProductoAsync(registro);
        }
        
        public void WebSalidaProducto(CapaGUI.ServiceMantenedorProducto.productos registro) {
            base.Channel.WebSalidaProducto(registro);
        }
        
        public System.Threading.Tasks.Task WebSalidaProductoAsync(CapaGUI.ServiceMantenedorProducto.productos registro) {
            return base.Channel.WebSalidaProductoAsync(registro);
        }
        
        public bool WebLogin(CapaGUI.ServiceMantenedorProducto.login login) {
            return base.Channel.WebLogin(login);
        }
        
        public System.Threading.Tasks.Task<bool> WebLoginAsync(CapaGUI.ServiceMantenedorProducto.login login) {
            return base.Channel.WebLoginAsync(login);
        }
    }
}
