//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceMantenedorProveedor {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorProveedor.WebServiceMantenedorProveedorSoap")]
    public interface WebServiceMantenedorProveedorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webGuardarTransaccionProveedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webGuardarTransaccionProveedor(CapaGUI.ServiceMantenedorProveedor.proveedor prov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webGuardarTransaccionProveedor", ReplyAction="*")]
        System.Threading.Tasks.Task webGuardarTransaccionProveedorAsync(CapaGUI.ServiceMantenedorProveedor.proveedor prov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webActualizarProveedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webActualizarProveedor(CapaGUI.ServiceMantenedorProveedor.proveedor prov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webActualizarProveedor", ReplyAction="*")]
        System.Threading.Tasks.Task webActualizarProveedorAsync(CapaGUI.ServiceMantenedorProveedor.proveedor prov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webEliminarProveedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webEliminarProveedor(string rut_prov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webEliminarProveedor", ReplyAction="*")]
        System.Threading.Tasks.Task webEliminarProveedorAsync(string rut_prov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webConsultaProveedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webConsultaProveedor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webConsultaProveedor", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webConsultaProveedorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webPosicionProveedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceMantenedorProveedor.proveedor webPosicionProveedor(int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webPosicionProveedor", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceMantenedorProveedor.proveedor> webPosicionProveedorAsync(int pos);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class proveedor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rut_provField;
        
        private string nombre_provField;
        
        private string comuna_provField;
        
        private string ciudad_provField;
        
        private int numero_provField;
        
        private string direccion_provField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Rut_prov {
            get {
                return this.rut_provField;
            }
            set {
                this.rut_provField = value;
                this.RaisePropertyChanged("Rut_prov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre_prov {
            get {
                return this.nombre_provField;
            }
            set {
                this.nombre_provField = value;
                this.RaisePropertyChanged("Nombre_prov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Comuna_prov {
            get {
                return this.comuna_provField;
            }
            set {
                this.comuna_provField = value;
                this.RaisePropertyChanged("Comuna_prov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Ciudad_prov {
            get {
                return this.ciudad_provField;
            }
            set {
                this.ciudad_provField = value;
                this.RaisePropertyChanged("Ciudad_prov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Numero_prov {
            get {
                return this.numero_provField;
            }
            set {
                this.numero_provField = value;
                this.RaisePropertyChanged("Numero_prov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Direccion_prov {
            get {
                return this.direccion_provField;
            }
            set {
                this.direccion_provField = value;
                this.RaisePropertyChanged("Direccion_prov");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorProveedorSoapChannel : CapaGUI.ServiceMantenedorProveedor.WebServiceMantenedorProveedorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorProveedorSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceMantenedorProveedor.WebServiceMantenedorProveedorSoap>, CapaGUI.ServiceMantenedorProveedor.WebServiceMantenedorProveedorSoap {
        
        public WebServiceMantenedorProveedorSoapClient() {
        }
        
        public WebServiceMantenedorProveedorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorProveedorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorProveedorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorProveedorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void webGuardarTransaccionProveedor(CapaGUI.ServiceMantenedorProveedor.proveedor prov) {
            base.Channel.webGuardarTransaccionProveedor(prov);
        }
        
        public System.Threading.Tasks.Task webGuardarTransaccionProveedorAsync(CapaGUI.ServiceMantenedorProveedor.proveedor prov) {
            return base.Channel.webGuardarTransaccionProveedorAsync(prov);
        }
        
        public void webActualizarProveedor(CapaGUI.ServiceMantenedorProveedor.proveedor prov) {
            base.Channel.webActualizarProveedor(prov);
        }
        
        public System.Threading.Tasks.Task webActualizarProveedorAsync(CapaGUI.ServiceMantenedorProveedor.proveedor prov) {
            return base.Channel.webActualizarProveedorAsync(prov);
        }
        
        public void webEliminarProveedor(string rut_prov) {
            base.Channel.webEliminarProveedor(rut_prov);
        }
        
        public System.Threading.Tasks.Task webEliminarProveedorAsync(string rut_prov) {
            return base.Channel.webEliminarProveedorAsync(rut_prov);
        }
        
        public System.Data.DataSet webConsultaProveedor() {
            return base.Channel.webConsultaProveedor();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webConsultaProveedorAsync() {
            return base.Channel.webConsultaProveedorAsync();
        }
        
        public CapaGUI.ServiceMantenedorProveedor.proveedor webPosicionProveedor(int pos) {
            return base.Channel.webPosicionProveedor(pos);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceMantenedorProveedor.proveedor> webPosicionProveedorAsync(int pos) {
            return base.Channel.webPosicionProveedorAsync(pos);
        }
    }
}
